pre-push:
  commands:
    biome-check:
      glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
      run: bunx @biomejs/biome check --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {push_files}
    textlint-docs-ja:
      glob: "docs/ja/*.md"
      run: "bun lint:docs:ja"
